default: &default
  adapter: postgresql
  pool: 5
  encoding: utf8
  timeout: 5000

development:
  <<: *default
  database: krusty-taste-api_development

test:
  <<: *default
  database: krusty-taste-api_test

production:
  <<: *default
  database: krusty-taste-api
